language: php
cache: bundler
php:
  - '7.1'

before_script:
  - bundle install
  - mkdir -p _data

script:
  - php news.php
  - bundler exec jekyll build
  - echo "forestguild.club" > _site/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: false
  local-dir: _site
  on:
    branch: master

after_deploy:
  - php clean-cache.php
