title: "Гильдия Ясный Лес @ EU Галакронд"
description: >- # this means to ignore newlines until "baseurl:"
  Гильдия Ясный Лес, World of Warcraft, EU Галакронд.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://forestguild.club" # the base hostname & protocol for your site, e.g. http://example.com
repository: rakshazi/forestguild.club
links:
  - name: Discord
    url: https://discord.gg/v9mNxAS
    class: text-danger
  - name: VK
    url: https://vk.com/jasnijles
    class:
  - name: Оружейная
    url: https://eu.battle.net/wow/ru/guild/galakrond/Ясный_Лес/
    class:
  - name: WoWProgress
    url: https://www.wowprogress.com/guild/eu/галакронд/Ясный+Лес
    class:
  - name: Raider.IO
    url: https://raider.io/guilds/eu/galakrond/Ясный%20Лес
    class:

rt:
  date: "Воскресенье-четверг 19:00-22:00 МСК"
  setup:
    default: "2 / 4 / 14"
    modifiable: true
  requirements:
    ilvl: 330
    flasks: 1
  raid:
    name: "Ульдир"
    difficulty: "Нормал"
    bosses: 8
    min: 7
    max: 8
  description: "Ежедневно (кроме пятницы-субботы). В 19:00 уже заходим в рейд, приходить в дискорд нцжно за 20-30 минут до начала."

# Build settings
markdown: kramdown
plugins: []
exclude:
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - updater
  - updater.php
  - .php_cs.dist
  - .travis.yml
