title: "Гильдия Ясный Лес @ EU Галакронд" #meta title
name: "Ясный Лес" #brand name, for menu
description: Гильдия Ясный Лес, World of Warcraft, EU Галакронд.
baseurl: ""
url: "https://forestguild.club"

# Integrations
github: rakshazi/forestguild.club
realm: galakrond
disqus: forestguild
verification:
  yandex: 0e76a0023e630508
  google: HyXyjl__ZWM8pD-mJqSaPIR2wVBFXVr25u0zwJkENfY
analytics:
  yandex: 50342920
  google: UA-113486799-3
video:
  today: 24 # WoW News playlist's last video index.
  streams: #twitch users
    - akulenokwow

# Assets
assets:
  head:
    - url: /assets/css/bootstrap.min.css
      type: css
  footer:
    - url: https://fonts.googleapis.com/css?family=Cuprum:700&amp;subset=cyrillic
      type: css
    - url: https://www.googletagmanager.com/gtag/js?id=UA-113486799-3
      async: true
      type: js
    - url: /assets/js/jquery.min.js
      type: js
    - url: /assets/js/bootstrap.bundle.min.js
      async: true
      type: js
    - url: https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.blackice.min.css
      integrity: sha256-gJADOPVrhQLECNkPq4IKJNH9g9TnCj3RzfhL/ToOn/E=
      type: css
    - url: https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js
      integrity: sha256-Ae7jmRrbL3hf1J/y22SYMPtx0wMVbG4g3HtpjioYuyk=
      type: js
    - url: https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/widgets/widget-filter.min.js
      integrity: sha256-PjucxS9eB9yoBEuahfglpLB5RQz+cEqMnAQQRVQqIUU=
      async: true
      type: js
    - url: https://wow.zamimg.com/widgets/power.js
      async: true
      type: js

# Build settings
markdown: kramdown

compress_html:
  clippings: all
  comments: all
  startings: all
  endings: all
  blanklines: false
  profile: false

exclude:
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - updater
  - updater.php
  - .php_cs.dist
  - .travis.yml

#plugins:
#  - jekyll-admin

# Raid time
rt:
  active: false
  date: "Среда и четверг 19:00-21:00 МСК "
  description: "В 19:00 уже заходим в рейд, приходить в дискорд нужно за 20-30 минут до начала."
  setup:
    default: "2 / 4 / 14"
    modifiable: true
  requirements:
    ilvl: 340
    flasks: 2
  raid: "Ульдир"
